In [6]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np

In [7]:
engine = create_engine('mysql+pymysql://root:210518aA@localhost:3306/stocks')

In [9]:
sql_stock_data = 'select * from stocks_dayk_duokong_20200125'
print(sql_stock_data)
df_stock_data = pd.read_sql_query(sql_stock_data,engine)
print('--------------------done--------------------------')

select * from stocks_dayk_duokong_20200125
--------------------done--------------------------


In [11]:
#################读取w1 与w2##################################
w1 = np.loadtxt("init_w1.txt",delimiter=',')
w2 = np.loadtxt("init_w2.txt",delimiter=',')
w2 = w2.reshape(-1,1)
#################根据文件内容，初始化w1与w2#####################

#print(w2[0:10,:])
print(w1[0:10,0:5])
print(w2[0:10])

[[ 0.51016764  0.52063552 -0.47427021 -0.33530229  0.69505654]
 [ 1.04168003 -0.44605734  0.63601078 -0.86688504  0.19307872]
 [ 0.918517    0.11703216 -0.14574368  0.58333847  1.03957917]
 [-0.79638608 -0.69771124  0.19311714  0.17681361 -0.35888606]
 [ 0.04124521  0.29755979  1.05351876  0.99239387 -0.67358842]
 [-0.14102161  0.06577621  0.38434658  0.04778562  0.09467385]
 [-1.02574763 -0.41886799  0.64875875  0.71195772 -0.39777627]
 [ 0.06857465  0.32192502 -0.4744816  -0.61842995 -0.0620756 ]
 [ 0.65993377  0.28706522  0.47569669 -0.59126929 -0.11243302]
 [-0.7764241  -0.34811224  0.24394684  0.51237494  0.16912317]]
[[-0.52691625]
 [ 0.64012957]
 [-0.48200588]
 [ 1.12607629]
 [-1.09850767]
 [-1.12340347]
 [ 0.38098403]
 [-1.14411218]
 [-0.00718101]
 [-0.94365217]]


In [12]:
code_gb = df_stock_data.groupby('code')

In [20]:
def train_class(test_data):
    print(test_data)
    days_count = test_data.shape[0]
    print(days_count)
    if test_data.loc[0,'duokong'] == 2:
        if test_data['duokong'].sum() ==2 :
            return True
    
    return False

In [21]:
for code,code_group in code_gb:
    df_dayk = code_gb.get_group(code)
    df_dayk = df_dayk.sort_values('date')
    day_count = df_dayk.shape[0] -1
    if train_class(df_dayk.loc[day_count-5:day_count,'duokong']):
        test_data_u = df_dayk.loc[day_count-5:day_count,['open','close','high','low','rise','exchange','ma5','ma10','ma20','ma30','ma60']]
        test_data_u['open'] = (test_data_u['open'] - test_data_u['open'].mean()) / test_data_u['open'].std()                  
        test_data_u['close'] = (test_data_u['close'] - test_data_u['close'].mean()) / test_data_u['close'].std()              
        test_data_u['high'] = (test_data_u['high'] - test_data_u['high'].mean()) / test_data_u['high'].std()                  
        test_data_u['low'] = (test_data_u['low'] - test_data_u['low'].mean()) / test_data_u['low'].std()                      
        test_data_u['rise'] = (test_data_u['rise'] - test_data_u['rise'].mean()) / test_data_u['rise'].std()                  
        test_data_u['exchange'] = (test_data_u['exchange'] - test_data_u['exchange'].mean()) / test_data_u['exchange'].std()  
        test_data_u['ma5'] = (test_data_u['ma5'] - test_data_u['ma5'].mean()) / test_data_u['ma5'].std()                      
        test_data_u['ma10'] = (test_data_u['ma10'] - test_data_u['ma10'].mean()) / test_data_u['ma10'].std()                  
        test_data_u['ma20'] = (test_data_u['ma20'] - test_data_u['ma20'].mean()) / test_data_u['ma20'].std()                  
        test_data_u['ma30'] = (test_data_u['ma30'] - test_data_u['ma30'].mean()) / test_data_u['ma30'].std()                  
        test_data_u['ma60'] = (test_data_u['ma60'] - test_data_u['ma60'].mean()) / test_data_u['ma60'].std()
        test_data_np = test_data_u.values   ###转换为 numpy
        test_data_np = test_data_np.reshape(1,-1)
        test_data_np = np.insert(test_data_np,0,1,axis=1)
        hid_input = np.matmul(x,w1)
        hid_output = np.tanh(hid_input)
        hid_output = np.insert(hid_output,0,1,axis=1)
        hpfs_input = np.matmul(hid_output,w2)
        hpfs_output = sigmond(hpfs_input)
        print(hpfs_output)
    break

115    0.0
116    0.0
117   -1.0
118    0.0
119    0.0
120    0.0
Name: duokong, dtype: float64
6


IndexingError: Too many indexers